"""Add audd_key to User

Revision ID: 73612f6d171d
Revises: 
Create Date: 2025-11-08 23:04:49.735208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73612f6d171d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audd_key', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('audd_key')

    # ### end Alembic commands ###
